### ISSUE TITLE
struggling with "doctr configure"

### ISSUE THREAD

**Issue by vstadnytskyi** [NSLS-II/scientific-python-cookiecutter#97]
Hi All,

It seems there are some changes since I used the cookie cutter last time. I am following the instructions on how to set-up new repository but I am getting this error. I cannot figure out why do I get it. Google did help me.

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/doctr", line 10, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/doctr/__main__.py", line 572, in main
    return process_args(get_parser(config=config))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/doctr/__main__.py", line 260, in process_args
    return args.func(args, parser)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/doctr/__main__.py", line 497, in configure
    upload_GitHub_deploy_key(deploy_key_repo, public_ssh_key, **login_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/doctr/local.py", line 312, in upload_GitHub_deploy_key
    return GitHub_post(data, DEPLOY_KEY_URL, **login_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/doctr/local.py", line 223, in GitHub_post
    GitHub_raise_for_status(r)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/doctr/local.py", line 212, in GitHub_raise_for_status
    r.raise_for_status()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.github.com/repos/vstadnytskyi/github-practice-template/keys

```

I have a feeling I have had this problem in the past :( I can figure out the solution again.

I think it is problem with my GitHub.

**Comment by vstadnytskyi** [comment]
I have a feeling I have had this problem in the past :( I can figure out the solution again.

**Comment by vstadnytskyi** [comment]
I have found a work around. The problem is with authentication and uploading of "github_deploy_key_vstadnytskyi_github_practice_template.enc" to GitHub. Why? I don't know yet. The key can be uploaded manually at later time. To make `doctr configure` work you need to add a parameter `doctr configure --no-upload-key`

https://github.com/drdoctr/doctr/issues/287

**Comment by vstadnytskyi** [comment]
It is nothing to do with this library, which is awesome! It is something to do with authorization. I have switch to ssh and now it all works. It will remain unresolved mystery for some time for me at least.

**Comment by asmeurer** [comment]
`doctr configure` was broken due to some changes in the GitHub API. Try updating to doctr 1.9.0 and running it again. Or you can use --no-upload, which should work in 1.8.0.
